version: '3.8'

services:
  # Backend API service
  api:
    build:
      context: ./secure-api-middleware
      dockerfile: dockerfile
    container_name: country-explorer-api
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - EMAIL_SERVICE=${EMAIL_SERVICE}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    volumes:
      - ./secure-api-middleware/logs:/app/logs
    networks:
      - country-explorer-network
    depends_on:
      - db

  # Frontend client service
  client:
    build:
      context: ./client
      dockerfile: dockerfile
    container_name: country-explorer-client
    restart: always
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://api:5000
      - NODE_ENV=production
    networks:
      - country-explorer-network
    depends_on:
      - api

  # Database service
  db:
    image: mysql:8.0
    container_name: country-explorer-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - country-explorer-network
    command: --default-authentication-plugin=mysql_native_password

networks:
  country-explorer-network:
    driver: bridge

volumes:
  mysql-data:
